import React, { memo } from 'react';
import {
  FaAws,
  FaBootstrap,
  FaCss3Alt,
  FaDocker,
  FaFigma,
  FaGitAlt,
  FaGithub,
  FaGithubAlt,
  FaGithubSquare,
  FaGitlab,
  FaHtml5,
  FaJava,
  FaJs,
  FaJsSquare,
  FaLaravel,
  FaNodeJs,
  FaNpm,
  FaPhp,
  FaPython,
  FaReact,
  FaSass,
  FaVuejs,
  FaWordpress,
  FaWordpressSimple,
} from 'react-icons/fa';
import {
  FiBox,
  FiCloud,
  FiCode,
  FiCpu,
  FiDatabase,
  FiGithub,
  FiGlobe,
  FiLayers,
  FiPackage,
  FiServer,
  FiTerminal,
} from 'react-icons/fi';
import {
  SiAlpinedotjs,
  SiAxios,
  SiBootstrap,
  SiCloudflare,
  SiCloudflarepages,
  SiCloudflareworkers,
  SiCloudinary,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFilament,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGithubpages,
  SiGitlab,
  SiHtml5,
  SiInertia,
  SiJavascript,
  SiJquery,
  SiLaravel,
  SiLivewire,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNuxtdotjs,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiReactrouter,
  SiRedis,
  SiRedux,
  SiSanity,
  SiSass,
  SiShadcnui,
  SiStrapi,
  SiStripe,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
} from 'react-icons/si';

const ICON_REGISTRY = Object.freeze({
  FaAws,
  FaBootstrap,
  FaCss3Alt,
  FaDocker,
  FaFigma,
  FaGitAlt,
  FaGithub,
  FaGithubAlt,
  FaGithubSquare,
  FaGitlab,
  FaHtml5,
  FaJava,
  FaJs,
  FaJsSquare,
  FaLaravel,
  FaNodeJs,
  FaNpm,
  FaPhp,
  FaPython,
  FaReact,
  FaSass,
  FaVuejs,
  FaWordpress,
  FaWordpressSimple,
  FiCloud,
  FiCode,
  FiCpu,
  FiDatabase,
  FiGithub,
  FiGlobe,
  FiLayers,
  FiPackage,
  FiServer,
  FiTerminal,
  SiAlpinedotjs,
  SiAxios,
  SiBootstrap,
  SiCloudflare,
  SiCloudflarepages,
  SiCloudflareworkers,
  SiCloudinary,
  SiCss3,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFilament,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiGithubpages,
  SiGitlab,
  SiHtml5,
  SiInertia,
  SiJavascript,
  SiJquery,
  SiLaravel,
  SiLivewire,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNuxtdotjs,
  SiOpenai,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiReactquery,
  SiReactrouter,
  SiRedis,
  SiRedux,
  SiSanity,
  SiSass,
  SiShadcnui,
  SiStrapi,
  SiStripe,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
});

function getRegisteredIcon(iconIdentifier) {
  if (!iconIdentifier || typeof iconIdentifier !== 'string') return null;
  return ICON_REGISTRY[iconIdentifier.trim()] || null;
}

const DynamicIcon = memo(function DynamicIcon({ iconIdentifier, className = '', size = 20, ...rest }) {
  const IconComponent = getRegisteredIcon(iconIdentifier);

  if (!IconComponent) {
    return <FiBox className={className} size={size} data-testid="icon-fallback" {...rest} />;
  }

  return React.createElement(IconComponent, {
    className,
    size,
    'data-testid': 'icon-resolved',
    ...rest,
  });
});

export default DynamicIcon;
